export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';
export const USER_SAVED = 'USER_SAVED';
export const SETTINGS_SAVED = 'SETTINGS_SAVED';
export const SETTINGS_PAGE_UNLOADED = 'SETTINGS_PAGE_UNLOADED';
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';
export const SET_PAGE = 'SET_PAGE';
export const APPLY_TAG_FILTER = 'APPLY_TAG_FILTER';
export const CHANGE_TAB = 'CHANGE_TAB';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const ADD_TAG = 'ADD_TAG';
export const REMOVE_TAG = 'REMOVE_TAG';
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
export const UPDATE_FIELD_EDITOR = 'UPDATE_FIELD_EDITOR';

export const GETUSERS = "GET_USERS";
export const USERSEARCH = "USER_SEARCH";
export const DEACTIVATE = "USER_DEACTIVATE";
export const REACTIVATE = "USER_REACTIVATE";

export const GETREFERENTS = "GET_REFERENTS";
export const REFERENTSEARCH = "REFERENT_SEARCH";
export const REGISTER_REFERENT = 'REGISTER_REFERENT';
export const ASSOCIATE_REFERENT = 'ASSOCIATE_REFERENT';
export const ASSOCIATE_REFERENT_PREFERENCE = 'ASSOCIATE_REFERENT_PREFERENCE';
export const ASSOCIATE_REFERENT_CLEAR_PREFERENCE = 'ASSOCIATE_REFERENT_CLEAR_PREFERENCE';
export const REFERENT_UPDATED = 'REFERENT_UPDATED';

export const LOCALE_SET = "LOCALE_SET";

export const GETORGANISMES = "GET_ORGANISMES";
export const ORGANISMESEARCH = "ORGANISME_SEARCH";
export const CREATE_ORGANISME = "CREATE_ORGANISME";
export const ORGANISME_UPDATED = 'ORGANISME_UPDATED';
export const UPDATE_ORGANISME = "UPDATE_ORGANISME";

export const CREATE_ORGANISME_REFERENT = "CREATE_ORGANISME_REFERENT";
export const UPDATE_ORGANISME_REFERENT = "UPDATE_ORGANISME_REFERENT";

export const CREATE_POINT_SERVICE = "CREATE_POINT_SERVICE";
export const UPDATE_POINT_SERVICE = "UPDATE_POINT_SERVICE";
export const GET_POINT_SERVICES = "GET_POINT_SERVICES";
export const POINT_SERVICE_SEARCH = "POINT_SERVICE_SEARCH";

export const CREATE_SERVICE = "CREATE_SERVICE";
export const UPDATE_SERVICE = "UPDATE_SERVICE";
export const GET_SERVICES = "GET_SERVICES";
export const SERVICE_SEARCH = "SERVICE_SEARCH";
export const ASSOCIATE_SERVICE = 'ASSOCIATE_SERVICE';

export const CREATE_DEMANDE_SERVICE = "CREATE_DEMANDE_SERVICE";
export const UPDATE_DEMANDE_SERVICE = "UPDATE_DEMANDE_SERVICE";
export const ADD_MOTIF = "ADD_MOTIF";
